version: '3.8'

services:
  api:
    build: .
    container_name: multiexchange_apiv2
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - ENV=production
    networks:
      - multiexchange_network


  celery:
    build: .
    container_name: multiexchange_celery
    restart: unless-stopped
    command: celery -A src.main.celery_app worker --loglevel=info
    environment:
      - ENV=production
    networks:
      - multiexchange_network
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: multiexchange_redis_v1
    restart: unless-stopped
    networks:
      - multiexchange_network
    volumes:
      - multiexchange_volume:/data

networks:
  multiexchange_network:
    driver: bridge

volumes:
  multiexchange_volume:
