apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitgetapi-deployment
  labels:
    app: bitgetapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitgetapi
  template:
    metadata:
      labels:
        app: bitgetapi
    spec:
      containers:
      - name: bitgetapi-container
        image: python:3
        ports:
        - containerPort: 8001
        env:
        - name: DB_HOST
          value: "182.18.0.10"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: bitgetapi-secrets
              key: DB_PASS
        - name: DB_NAME
          value: "main_db"
        - name: BRIGHTDATA_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: bitgetapi-secrets
              key: BRIGHTDATA_API_TOKEN
