apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-exchange-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-exchange
  template:
    metadata:
      labels:
        app: multi-exchange
    spec:
      containers:
      - name: multi-exchange
        image: python:3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: multi-exchange-service
spec:
  selector:
    app: multi-exchange
  ports:
  - port: 80
    targetPort: 80
